# Generated by Django 5.0.3 on 2024-03-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCompleto', models.CharField(max_length=50)),
                ('Asistencia', models.CharField(choices=[('pendiente', 'Pendiente'), ('cancelado', 'Cancelado'), ('confirmado', 'Confirmado')], default='pendiente', max_length=12)),
                ('Mesa', models.IntegerField()),
                ('Cancion', models.CharField(max_length=80)),
                ('Proteina', models.CharField(choices=[('cerdo', 'Cerdo'), ('pollo', 'Pollo'), ('res', 'Res'), ('pescado', 'Pescado')], default=False, max_length=10)),
                ('Restriccion', models.CharField(choices=[('mariscos', 'Soy alergico a los mariscos'), ('vegano', 'Soy vegano'), ('vegetariano', 'Soy vegetariano'), ('lacteos', 'Soy intolerante a los lacteos'), ('diabetico', 'Soy diabetico')], default=False, max_length=30)),
                ('Observaciones', models.CharField(default=False, max_length=100)),
            ],
        ),
    ]
