# Generated by Django 5.0.3 on 2024-03-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitados',
            options={'verbose_name_plural': 'Invitados'},
        ),
        migrations.AlterField(
            model_name='invitados',
            name='Cancion',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='invitados',
            name='Mesa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='invitados',
            name='Observaciones',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='invitados',
            name='Proteina',
            field=models.CharField(blank=True, choices=[('cerdo', 'Cerdo'), ('pollo', 'Pollo'), ('res', 'Res'), ('pescado', 'Pescado')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='invitados',
            name='Restriccion',
            field=models.CharField(blank=True, choices=[('mariscos', 'Soy alergico a los mariscos'), ('vegano', 'Soy vegano'), ('vegetariano', 'Soy vegetariano'), ('lacteos', 'Soy intolerante a los lacteos'), ('diabetico', 'Soy diabetico'), ('ninguna', 'Ninguna de las anteriores')], default=False, max_length=30),
        ),
    ]
