# Generated by Django 5.0.3 on 2024-03-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitados', '0002_alter_invitados_options_alter_invitados_cancion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitados',
            name='Mesa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
